[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=."

# Handle API routes through serverless functions
[[redirects]]
  from = "/api/livekit/*"
  to = "/.netlify/functions/livekit-:splat"
  status = 200

[[redirects]]
  from = "/api/gemini/*"
  to = "/.netlify/functions/gemini-:splat"
  status = 200

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers for CORS and security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"